### ISSUE TITLE
M2

### ISSUE THREAD

**Issue by Bfrench6** [TheUnderJackets/Project#1]
Guys, don't forget to edit AntLabMain in pkg1 and add your name and gt id in addition to your person# class and the readme

**Comment by willchristian343** [comment]
I'm having some difficulty at the moment committing through IntelliJ, I will try to get AntLabMain & my Java & readme files up by Thursday evening after going though some tutorials to get more comfortable with git.

**Comment by atsuh0124** [comment]
Personally, I find using the Terminal to be a lot easier if you know how to use it. Here's some general stuff that may be useful if you can use the command line, which since you use Linux, might be useful. (Note, you should be in the cloned local directory for this stuff.
What to do once you've modified the files you want for your commit.
`git add *`
`git commit -m "Enter Message Here"`
`git push origin master`
If you get an error message at that point, that means that your cloned directory is an outdated version, and you need to update your working cloned directory. Here's what to do at that point.
`git pull origin master`
This will bring the files from the repo into your working directory and attempt to merge them. If nothing happens, run `git status`. If it says clean directory, you should be good. If there is a merge conflict, it will say something like "Merge conflict, unmerged branches". If that's the case, open up the text file that is causing the merge conflict (iirc, the file is mentioned when you get the merge conflict. If not, use `git status` and it should tell you). The file will be marked up with >>>>>>>> and ========= and <<<<<<<<<. This breaks up the conflict into "areas" to be resolved. Manually resolve the conflict(s) and delete the markings. Then, run the following after saving.
`git add *`
`git commit -m "Enter Message Here"`
`git push origin master`
And with that, it SHOULD be updated on the github repo. If you get a rejected message, use
`git pull origin master` again, and it should work now. If you use this and weird things still happen, let me know.

**Comment by willchristian343** [comment]
Thanks that was very helpful. I just committed Person3.java, readme.p3.txt, and AntLabMain through the terminal and everything worked smoothly.
